#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---

# NOTE: dreg is deployed on a Jetstream server

gateway_data_store_hostname: "dreg.dnasequence.org"
gateway_data_store_resource_id: "js-156-72.jetstream-cloud.org_758cf5c0-71f4-4268-bb42-5ede23cfeea9"
real_user_data_dir: "/media/volume/sdb/gateway-user-data"
# Keep user_data_dir same as it was on old VM
user_data_dir: "/var/www/portals/gateway-user-data"
tusd_vhost_servername: "tus.dreg.scigap.org"
# Increase max upload size to 1GB
django_file_upload_max_file_size_mb: 1024

# TODO: while testing dreg-djangoapp, turn off SELinux, but turn it back on
# once it is installed for real
httpd_selinux_mode: "permissive"
# airavata_django_extra_dependencies:
#   - git+https://github.com/SciGaP/dreg-djangoapp.git@gbrowser#egg=dreg-djangoapp

# vhost_servername: "django.dreg.scigap.org"
vhost_servername: "dreg.js2.scigap.org"
# vhost_servername: "dreg.dnasequence.org"
vhost_ssl: True
ssl_certificate_file: "/etc/letsencrypt/live/{{ vhost_servername }}/cert.pem"
ssl_certificate_chain_file: "/etc/letsencrypt/live/{{ vhost_servername }}/fullchain.pem"
ssl_certificate_key_file: "/etc/letsencrypt/live/{{ vhost_servername }}/privkey.pem"
django_ssl_vhost_template: "{{ inventory_dir }}/host_vars/dreg/files/django-ssl-vhost.conf.j2"

## Keycloak related variables
tenant_domain: "cornelldna"
oauth_client_key: "{{ vault_oauth_client_key }}"
oauth_client_secret: "{{ vault_oauth_client_secret }}"

auth_options:
  password:
    name: "dREG"
#  external:

gateway_id: "cornelldna"
experiment_data_dir: "{{ user_data_dir }}/cornell-dnasequence"
gateway_data_store_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTs6k2lSt5nn+UF3N1rAko9WjdtHZ1xLcKxCG4+4AVMdTIeng12g+1qB5hIFiDgesT/D/nzoA27EFj5nWiYanxBySNgl1Re8kR0nEqQbR0zj1dSibmfjW+vmOZzEiNSrNoLlc4KbFgqFCRGIlZ1bWZ7yHtJ3I7xxfKhvvxCTzJ4K71v1aovnDTUYophy2lUsdOcOq84Qhv3ITZafgblz3mJSwVpnnI72IepzonzDUdcf/w0lKCl70L9MgQAZ2V4e9sQZWJLI5s1VtJsqKggtgI4goPyxXROoH9PTUZFqvvYjLGW8JVS9eZKblSKil09yckPfZCSk1i/UD/uY6O7bjf"

admin_emails: "[('Zhong Wang', 'zw355@cornell.edu'), ('SGRC', 'sgrc-iu-group@iu.edu')]"
portal_title: "dREG Portal"

django_google_analytics_tracking_id: "UA-111528347-3"

...
