$ANSIBLE_VAULT;1.1;AES256
32646566346165633263613063613465353634316261333737653431646232653433346636616635
3136393565636162623536376661386138383733393637610a646138353030353138373739393839
64353833616133633431333032306635333630313835333865313031363733373436303266616466
3863366437643233630a366265316631336162623666303064343861646234326132663863346236
63313364303063636136666365343164616336613837373133376232343165666139316165663961
30316435313838656437346437363365663835656138353937643238363564373363623965336262
34383964383363323862353932363538613432373765383762323138343435333239663939373533
62373264353763363666623063393934376631336133623237353365663365303063366233336131
30373836353566643430336436646138633237356265306438383937393937646234663831336436
38616438663836313866393563363036396131373164616563653162333835656130376132316430
65353864313337303366386566646435643065636662316563333734383432346431373536356533
36393131383131663132613939386537336131353961653537646230326632373966303937613532
62396436656161663264393335366633323533636666613364303364316134306439306334663065
30623065333537643930373962663264343766356636333937383135333164363635396536316338
36353436626436303938316638383632316233623562353930376238373038633964303431366135
63623162306335353234393737623137356361653162633436666132333737316461663061373562
32363836376238396239616163666338393839343865353866326166353532656361