$ANSIBLE_VAULT;1.1;AES256
61376631616161353462343462316538376632616463376630343332373432383835313363653565
6136326631383532653163626337616661326432356364630a633636613835616136333939386463
33373035383563643536666262663661336637393231663231623534393837303634636135613732
3466653134363039640a326232393938633134383538386131306364626561383033313761336634
39326337626463396533613332303331343736333735636462666363626630316362323735376163
32653862353031333839376235346131333539613830313933333738616636343731396666656333
66396165643633353534373563313861386639313363343165366432623535303737326464666665
37613862636332393437383533373334646366663539373931613364353935626663343639666363
65613639363639346463333031313764653934353565323662303038363039333638346363336365
31633231393635396635666461636338323138363834343932353930626531346337323435383462
66653233326336363133636530303330323464616138613430353966353662663366323462653162
30636533373639366234333234623635323736623934666166373637366334353731376339393634
63323863393862643131656264343238343531633337626234366235386331383631363565363662
61666631626162636561373332353736356639326566313561623732656631316338376266623563
31306234353566366331613565383136623163393230373239383630656635356530326233646337
31663436626337353632353332663061383232646530366362383034653638316130396339666533
66643066396566626237356431623163623538356632333733346334353735643766353764303433
3063663237646466353765663438363237333630383763303534
