#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
################################################################################
# Setup and run rabbitmq

# Ubuntu: Add RabbitMQ APT repository
- name: Install prerequisites for RabbitMQ (Ubuntu)
  apt:
    name:
      - curl
      - gnupg2
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Add RabbitMQ Erlang signing key (Ubuntu)
  shell: curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | gpg --dearmor -o /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg
  become: yes
  when: ansible_os_family == "Debian"
  args:
    creates: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg

- name: Add RabbitMQ server signing key (Ubuntu)
  shell: curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | gpg --dearmor -o /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg
  become: yes
  when: ansible_os_family == "Debian"
  args:
    creates: /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg

- name: Map Ubuntu release to RabbitMQ repository codename (use jammy for noble)
  set_fact:
    rabbitmq_ubuntu_codename: "{{ 'jammy' if ansible_distribution_release == 'noble' else ansible_distribution_release }}"
  when: ansible_os_family == "Debian"

- name: Add RabbitMQ Erlang repository (Ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg arch=amd64] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ rabbitmq_ubuntu_codename | default('jammy') }} main"
    state: present
    filename: rabbitmq-erlang
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Add RabbitMQ server repository (Ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg arch=amd64] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu {{ rabbitmq_ubuntu_codename | default('jammy') }} main"
    state: present
    filename: rabbitmq-server
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

# Rocky/CentOS: Add RabbitMQ RPM repository
- name: Install erlang from RabbitMQ repository (Rocky/CentOS)
  yum:
    name: "https://github.com/rabbitmq/erlang-rpm/releases/download/v{{ rabbitmq_erlang_version }}/erlang-{{ rabbitmq_erlang_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  become: yes
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Add RabbitMQ YUM repository (Rocky/CentOS)
  yum_repository:
    name: rabbitmq_server
    description: RabbitMQ Server
    baseurl: "https://packagecloud.io/rabbitmq/rabbitmq-server/el/{{ ansible_distribution_major_version }}/$basearch"
    gpgcheck: yes
    gpgkey: "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

# Install RabbitMQ server
- name: Install RabbitMQ server (Ubuntu)
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Install RabbitMQ server (Rocky/CentOS)
  yum:
    name: rabbitmq-server
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "RedHat"

- name: allow only selected networks to access Airavata RabbitMQ
  firewalld:
    zone: public
    permanent: yes
    state: enabled
    rich_rule: rule family=ipv4 source address="{{ item }}" port port="{{ rabbitmq_port }}" protocol=tcp accept
    immediate: yes
  with_items:
    - "{{ rabbitmq_subnets }}"
  become: yes

- name: allow only selected networks to access Airavata RabbitMQ Management Console
  firewalld:
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
    rich_rule: rule family=ipv4 source address="{{ item }}" port port="{{ management_plugin_port }}" protocol=tcp accept
  with_items:
    - "{{ rabbitmq_subnets }}"
  become: yes

- name: Edit /etc/hosts file
  lineinfile: dest=/etc/hosts line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn.split('.')[0] }}"
  notify:
    - restart rabbitmq
  become: yes

- name: Start Rabbitmq server
  service: name=rabbitmq-server state=started enabled=yes
  become: yes

- name: Enable rabbitmq management plugin
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify:
    - restart rabbitmq
  become: yes

- name: Create rabbitmq vhost {{ rabbitmq_vhost }}
  rabbitmq_vhost: name="{{ rabbitmq_vhost }}" state=present
  become: yes

- name: Add user {{ rabbitmq_user }} to vhost {{ rabbitmq_vhost }}  and give permission
  rabbitmq_user: user="{{ rabbitmq_user }}"
                 password="{{ rabbitmq_password }}"
                 vhost="{{ rabbitmq_vhost }}"
                 tags="administrator"
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  become: yes

- name: restart rabbitmq
  service: name=rabbitmq-server state=restarted
  become: yes

...
