#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

grpc:
  server:
    port: 19900
    max-inbound-message-size: 20971520

server:
  port: 18880
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: "jdbc:mariadb://airavata.host:13306/app_catalog"
    username: "airavata"
    password: "123456"
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: AppCatalogPool
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

airavata:
  server:
    url: airavata.host
    port: 9930
    truststore:
      path: keystores/airavata.jks
  storageResourceId: airavata.host_77116e91-f042-4d3a-ab9c-3e7b4ebcd5bd
  storagePath: /tmp
  cluster:
    applicationInterfaceId: AiravataAgent_f4313e4d-20c2-4bf6-bff1-8aa0f0b0c1d6
  tunnel:
    serverHost: airavata.host
    serverPort: 17000
    serverToken: airavata
    serverApiUrl: http://airavata.host:8000
