grpc:
  server:
    port: 19900
    max-inbound-message-size: 20971520

server:
  port: 18880
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: "jdbc:mariadb://localhost:13306/app_catalog"
    username: "root"
    password: "123456"
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: AppCatalogPool
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

airavata:
  server:
    url: scigap02.sciencegateways.iu.edu
    port: 9930
    truststore:
      path: CHANGE_ME
  storageResourceId: gf4.ucs.indiana.edu_61552681-96f0-462a-a36c-a62a010bffc6
  storagePath: /var/www/portals/gateway-user-data
  cluster:
    applicationInterfaceId:
      expanse: AiravataAgent_f4313e4d-20c2-4bf6-bff1-8aa0f0b0c1d6
      jetstream: UPDATE
