#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
doc_root_dir: "/var/www/{{ gateway_id }}"
user_data_dir: "/var/www/user_data"
# real_user_data_dir is the same as user_data_dir but without symbolic links in it
real_user_data_dir: "{{ user_data_dir }}"
vhost_servername: "{{ groups['pga'][0] }}"
vhost_ssl: False
httpd_confd_file_location:
 RedHat: "/etc/httpd/conf.d/pga-{{ gateway_id }}.conf"
 Debian: "/etc/apache2/sites-available/pga-{{ gateway_id }}.conf"
default_conf_file_location:
 RedHat: "/etc/httpd/conf.d/default.conf"
 Debian: "/etc/apache2/sites-available/default.conf"
ssl_conf_file_location:
 RedHat: "/etc/httpd/conf.d/ssl.conf"
 # TODO: Debian file layout is different, so we really need a different ssl.conf for Debian
 Debian: "/etc/apache2/mods-available/ssl.conf"
httpd_name:
 Debian: apache2
 RedHat: httpd
httpd_log_dir:
 Debian: /var/log/apache2
 RedHat: /var/log/httpd

# PHP Config values set in httpd vhost config

# Allow uploading files up to 64MB in size.
# NOTE: if you change one of these values you will need to change the other one likewise.
php_upload_max_filesize: "64M"
php_post_max_size: "64M"

pga_vhost_template: "pga-vhost.conf.j2"
pga_ssl_vhost_template: "pga-ssl-vhost.conf.j2"
pga_config_template: "pga_config.php.j2"
pga_default_conf_template: "default.conf.j2"
pga_ssl_conf_template: "ssl.conf.j2"

## WSO2 IS related variables
tenant_domain: "prod.testdrive"
admin_username: "tdaadmin"
admin_password: "SciDeploy"
oauth_client_key: "RuLl_Uw7i_KXaLoAGJkiasTfyBYa"
oauth_client_secret: "vD9yi2ANkChzgWiih3RahrIcfsoa"
oauth_grant_type: "password"
oauth_service_url: "https://iam.scigap.org/auth"
admin_role_name: "admin"
admin_readonly_role_name: "admin-read-only"
user_role_name: "gateway-user"
initial_role_name: "user-pending"
auth_verify_peer: "false"
auth_options:
  - name: "{{ portal_title }}"
    oauth_grant_type: "password"
#    oauth_authorize_url_extra_params: "kc_idp_hint=oidc"
oauth_callback_url: "http://{{ vhost_servername }}/callback-url"


## Airavata Client related variables
#airavata_server: "tls://gw77.iu.xsede.org"
pga_repo: "https://github.com/apache/airavata-php-gateway.git"
pga_git_branch: "master"
airavata_server: "{{ groups['api-orch'][0] }}"
airavata_port: "8930"
airavata_profile_service_server: "{{ airavata_server }}"
airavata_profile_service_port: "8962"
gateway_id: "{{ default_gateway }}"
# relative to document root dir
experiment_data_dir: "{{ user_data_dir }}"
gateway_data_store_resource_id: "js-170-103.jetstream-cloud.org_6497a464-3121-4b64-a7cb-d195b0a26c19"
gateway_data_store_ssh_public_key: ""
data_sharing_enabled: "true"

## Portal related variables
super_admin_portal: "true"
admin_emails: "'sgg@iu.edu'"
portal_email_username: "ansibletestairavata@gmail.com"
portal_email_password: "ansibletestairavata12"
portal_theme: "base"
portal_theme_repo: ""
portal_title: "Airavata PHP Gateway"
pga_google_analytics_id: ""
# When pga_reroute_to_django is true, pga_airavata_django_url should also be set
pga_reroute_to_django: false

pga_default_http_port: 80
pga_default_https_port: 443
...
