---
#Master playbook
- hosts: zookeeper
  tags: zookeeper, airavata
  roles:
    - env_setup
    - java
    - zookeeper

- hosts: rabbitmq
  tags: rabbitmq, airavata
  roles:
    - env_setup
    - rabbitmq

- hosts: database
  tags: mysql , airavata
  roles:
    - env_setup
    - role: database
      become: yes
      become_user: "{{user}}"

- hosts: wso2is
  tags: wso2is
  roles:
    - env_setup
    - java
    - role: wso2_is
      become: yes
      become_user: "{{user}}"


- hosts: gfac
  tags: gfac, airavata
  roles:
    - env_setup
    - java
    - role: common
      become: yes
      become_user: "{{user}}"
    - role: gfac
      become: yes
      become_user: "{{user}}"

- hosts: api-orch
  tags: api-orch, airavata
  roles:
    - env_setup
    - java
    - role: common
      become: yes
      become_user: "{{user}}"
    - role: api-orch
      become: yes
      become_user: "{{user}}"

- hosts: registry
  tags: registry, airavata
  roles:
    - env_setup
    - java
    - role: common
      become: yes
      become_user: "{{user}}"
    - role: registry
      become: yes
      become_user: "{{user}}"

- hosts: pga
  tags: pga
  roles:
    - env_setup
    - pga

...
