#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
keycloak_version: "24.0.0"
keycloak_downlaod_url: "https://github.com/keycloak/keycloak/releases/download/{{keycloak_version}}/keycloak-{{keycloak_version}}.tar.gz"
keycloak_install_dir: "keycloak-{{keycloak_version}}"
keycloak_db_connector_name: "mysql-connector-j-8.0.33.jar"
# TODO MySQL Connector/J is GPL licensed. Instead use MariaDB Connector
mysql_db_connector_download_url: "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-8.0.33.tar.gz"
mysql_connector_dir_name: "mysql-connector-j-8.0.33"
mysql_connector_archive_name: "mysql-connector-j-8.0.33.tar.gz"
# keycloak_ssl_keystore_file: "airavata.p12"
# keycloak_ssl_keystore_file_name: "airavata.p12"
# keycloak_ssl_keystore_password: "Airavata"
# Set these in inventories/<env>/group_vars/all/vault.yml:
# - keycloak_master_account_username (Keycloak admin username)
# - keycloak_master_account_password (Keycloak admin password - use vault!)
# - keycloak_db_username (database username for Keycloak)
# - keycloak_db_password (database password for Keycloak - use vault!)
keycloak_master_account_username: "CHANGEME"
keycloak_master_account_password: "CHANGEME"
# keycloak_server_port: "443"
keycloak_java_home: "{{ java_home }}"

keycloak_db_vendor: "mariadb"
keycloak_db_host: "localhost"
keycloak_db_port: "3306"
keycloak_db_schema_name: "keycloak"
keycloak_db_url: "jdbc:mysql://{{keycloak_db_host}}:{{keycloak_db_port}}/{{keycloak_db_schema_name}}"
keycloak_quarkus_db_url: "jdbc:{{ keycloak_db_vendor }}://{{keycloak_db_host}}:{{keycloak_db_port}}/{{keycloak_db_schema_name}}"
keycloak_db_username: "CHANGEME"
keycloak_db_password: "CHANGEME"
keycloak_db_pool_size: "20"

keycloak_realm_import_enabled: true
keycloak_realm_name: "default"
keycloak_realm_import_src: "realm-default.json.j2"
keycloak_realm_import_dir: "{{ user_home }}/keycloak-realms"
keycloak_realm_import_filename: "realm-default.json"
keycloak_realm_import_path: "{{ keycloak_realm_import_dir }}/{{ keycloak_realm_import_filename }}"
keycloak_realm_import_marker: "{{ keycloak_realm_import_dir }}/.imported-{{ keycloak_realm_name }}"
keycloak_logout_url: "https://{{ keycloak_vhost_servername }}/"

keycloak_vhost_servername: "changeme.org"
keycloak_ssl_certificate_file: "/etc/letsencrypt/live/{{ keycloak_vhost_servername }}/cert.pem"
keycloak_ssl_certificate_chain_file: "/etc/letsencrypt/live/{{ keycloak_vhost_servername }}/fullchain.pem"
keycloak_ssl_certificate_key_file: "/etc/letsencrypt/live/{{ keycloak_vhost_servername }}/privkey.pem"
...
