#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
keycloak_version: "2.5.4.Final"
keycloak_downlaod_url: "https://downloads.jboss.org/keycloak/{{keycloak_version}}/keycloak-{{keycloak_version}}.tar.gz"
keycloak_install_dir: "keycloak-{{keycloak_version}}"
keycloak_db_connector_name: "mysql-connector-java-5.1.41"
# keycloak_ssl_keystore_file: "keycloak.jks"
# keycloak_ssl_keystore_file_name: "keycloak.jks"
# keycloak_ssl_keystore_password: "Airavata"
mysql_db_connector_download_url: "https://dev.mysql.com/get/Downloads/Connector-J/{{keycloak_db_connector_name}}.tar.gz"
keycloak_master_account_username: "username"
keycloak_master_account_password: "password"
# keycloak_server_port: "443"
keycloak_java_home: /usr/lib/jvm/java-1.8.0

keycloak_db_host: "localhost"
keycloak_db_port: "3306"
keycloak_db_schema_name: "keycloak"
keycloak_db_url: "jdbc:mysql://{{keycloak_db_host}}:{{keycloak_db_port}}/{{keycloak_db_schema_name}}"
keycloak_db_username: "username"
keycloak_db_password: "password"
keycloak_db_pool_size: "20"

keycloak_vhost_servername: "changeme.org"
keycloak_ssl_certificate_file: "/etc/letsencrypt/live/{{ keycloak_vhost_servername }}/cert.pem"
keycloak_ssl_certificate_chain_file: "/etc/letsencrypt/live/{{ keycloak_vhost_servername }}/fullchain.pem"
keycloak_ssl_certificate_key_file: "/etc/letsencrypt/live/{{ keycloak_vhost_servername }}/privkey.pem"
...
