$ANSIBLE_VAULT;1.1;AES256
35393463623034396661646365323430386238323037643233363431643463353937653038366266
3335346534353634343632306163636566653666363562650a363839616365623364366434666537
37333436376430346630613033623163633637626433313763666533306633643065333431616235
6463343263373464320a633537626432353533623139623438363834353464366335633163303162
64623433363938633131613936333037646562623233353833613734623934343731656130613266
35373733663962373462366234663137666634636163323733623830613164616432316266356366
31633231316439633862666431626235353530623365623963636161386232366336303138336564
33363064646637336232383232343261333932393031653364656565326365646136636531323639
66626539636637626336313365333034363834393636303866333534633761656631
