$ANSIBLE_VAULT;1.1;AES256
30613833613339306564376233636363653334363264316639303234316163333632363033353065
3962376364316136343430646437616134653437386238620a356563326231623631373566346434
37343366663630346464356332633135363635303236333336623634633865383538346538626639
3863333836666530340a636363323061393462643238633033373730373335313035656535313334
36386532616439363439343538356662323766363333346165356334633635303637626539323532
62326666343632383531663365343664313930343139326137373565303437373630383132653334
32336230383361336262663839376135393235383933356561323530396164343331616136616163
65313265613730626133353930363234616130393035666330633261346638633733653037383438
61353633643530626362323639363835316265303730363364323363363438346163643637643563
31326232626336653466393064316231366466613465663063643139636666303266316536333634
64646362633733386332303433316631313936386235346634623062313338633537666432653865
37613339396266626333643836343030326562323033363234656366343063303130386234623662
36396239656539303365636539316530626563396665666134616430336430386330633366303864
36373366383033303332363263343831326463383238633766323862393336326665643162343062
61376139346538383965336334326563323332323936353439663935323238326436353162376336
36323030333262633764633862613765643934303430613438326535666235343535663735373639
62333864356630376537306163623536613330623537613239663133643065323533653561643435
33636431373962363634336536363437656433306564653836663431323331386137646630316439
346666336436373432633264303934326139
